# Generated by Django 4.0.4 on 2022-05-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviations',
            fields=[
                ('abv', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('entity', models.CharField(max_length=264, unique=True)),
                ('asset_type', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
