# Generated by Django 4.0.4 on 2022-05-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbreviations',
            name='asset_type',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='abbreviations',
            name='entity',
            field=models.CharField(max_length=264),
        ),
    ]
